#This will be the node that all nodes connect to initially
peer_addresses:
- 127.0.0.1:8002
- 127.0.0.1:8003
server_address: 127.0.0.1:8001
capacity: 3
connection_check_interval: 30
mining: true
# configuration for mining
minimum_mining_delay: 10
mining_delay_interval: 10
minimum_broadcast_delay: 5
broadcast_delay_interval: 5
minimum_add_num: 10
add_num_range: 30
