#This will be the node that all nodes connect to initially
peer_addresses:
- 127.0.0.1:8002
- 127.0.0.1:8003
server_address: 127.0.0.1:8001
capacity: 3
connection_check_interval: 30
mining: true
# configuration for mining
mining_delay_lowerbound: 10
mining_delay_upperbound: 20
broadcast_delay_lowerbound: 1
broadcast_delay_upperbound: 3
add_num_lowerbound: 10
add_num_upperbound: 20