peer_addresses:
- 127.0.0.1:8001
server_address: 127.0.0.1:8002
capacity: 2
connection_check_interval: 30
mining: true
minimum_mining_delay: 10
mining_delay_interval: 10
minimum_broadcast_delay: 5
broadcast_delay_interval: 5
minimum_add_num: 10
add_num_range: 30
